export const Resources = [
    ['background', 'res/image/base.png'],
    ['begin', 'res/image/begin.png'],
    ['lijuan', 'res/image/lijuan.png'],
    ['liwu1', 'res/image/liwu1.png'],
    ['liwu2', 'res/image/liwu2.png'],
    ['liwu3', 'res/image/liwu3.png'],
    ['liwuopen1', 'res/image/liwuopen1.png'],
    ['liwuopen2', 'res/image/liwuopen2.png'],
    ['liwuopen3', 'res/image/liwuopen3.png'],
    ['qipao', 'res/image/qipao.png'],
    ['second', 'res/image/second.png'],
    ['tiaowen', 'res/image/tiaowen.png'],
    ['yishouji', 'res/image/yishouji.png'],
];